kind: pipeline
type: kubernetes
name: Build & Publish ARM64

platform:
  os: linux
  arch: arm64

- name: publish  
  image: plugins/docker:linux-arm64
  pull: if-not-exists
  settings:
    repo: basedmeezus/rpi_availibility_bot
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

---

kind: pipeline
type: kubernetes
name: Build & Publish AMD64

platform:
  os: linux
  arch: amd64

- name: publish  
  image: plugins/docker:amd64
  pull: if-not-exists
  settings:
    repo: basedmeezus/rpi_availibility_bot
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
