kind: pipeline
type: kubernetes
name: Build & Publish ARM64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push
    - tag
    - pull_request
steps:
- name: publish  
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: basedmeezus/drone_testing
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

---

kind: pipeline
type: kubernetes
name: Build & Publish AMD64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - tag
    - pull_request
steps:
- name: publish  
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: basedmeezus/drone_testing
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
