kind: pipeline
type: kubernetes
name: Build & Publish ARM64

steps:
- name: start_docker
  image: docker:dind
  pull: if-not-exists
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 50 # give docker enough time to start
  - docker run --privileged --rm tonistiigi/binfmt --install all

- name: publish  
  image: thegeeklab/drone-docker-buildx:latest
  pull: if-not-exists
  privileged: true
  settings:
    repo: basedmeezus/rpi_availibility_bot
    auto_tag: true
    auto_tag_suffix: linux-arm64
    platforms:
      - linux/arm64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}



---

kind: pipeline
type: kubernetes
name: Build & Publish ARM

steps:

- name: start docker
  image: docker:dind
  pull: if-not-exists
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 50 # give docker enough time to start
  - docker run --privileged --rm tonistiigi/binfmt --install all


- name: build & publish  
  image: thegeeklab/drone-docker-buildx:latest
  pull: if-not-exists
  privileged: true
  settings:
    repo: basedmeezus/rpi_availibility_bot
    auto_tag: true
    auto_tag_suffix: linux-arm
    platforms: 
      - linux/arm
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}




---

kind: pipeline
type: kubernetes
name: Build & Publish AMD64

steps:

- name: start docker
  image: docker:dind
  pull: if-not-exists
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 50 # give docker enough time to start
  - docker run --privileged --rm tonistiigi/binfmt --install all


- name: build & publish  
  image: thegeeklab/drone-docker-buildx:latest
  pull: if-not-exists
  privileged: true
  settings:
    repo: basedmeezus/rpi_availibility_bot
    auto_tag: true
    auto_tag_suffix: linux-amd64
    platforms: 
      - linux/amd64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD


services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}


