kind: pipeline
type: kubernetes
name: Build & Publish AMD64

platform:
  arch: amd64
  os: linux

trigger:
  event:
    - push
    - tag
    - pull_request
steps:
- name: publish  
  image: plugins/docker
  pull: always
  settings:
    repo: basedmeezus/drone_testing
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
---

kind: pipeline
type: kubernetes
name: Build & Publish ARM64

platform:
  arch: arm64
  os: linux

trigger:
  event:
    - push
    - tag
    - pull_request
steps:
- name: publish  
  image: plugins/docker
  pull: always
  settings:
    repo: basedmeezus/drone_testing
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

---
kind: pipeline
type: kubernetes
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    spec: manifest.tmpl
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: DOCKER_PASSWORD
    username:
      from_secret: DOCKER_USERNAME

depends_on:
- Build & Publish AMD64
- Build & Publish ARM64
